version: '3.8'

services:
  danceemotion:
    image: danceemotionweb:latest
    tty: true
    stdin_open: true
    container_name: danceemotion
    ports:
      # Nota: risponde solo alle richieste interne
      # (utilizzo con reverse proxy NGINX)
      - "127.0.0.1:6568:6568"
    volumes:
      # Mappa il file del database locale del server dentro il container
      - ./danceemotion.db:/app/database/danceemotion.db
      # Mappa le cartelle dinamiche dell'applicazione
      - ./images/:/app/public/images/
      - ./videos/:/app/public/videos/
      - ./uploads/attachment/:/app/uploads/attachment/
      - ./uploads/dancer/:/app/uploads/dancer/
      - ./uploads/school/:/app/uploads/school/
    restart: always
